name: Java Maven CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Find and display pom.xml location
        run: |
          echo "Searching for pom.xml..."
          find . -name "pom.xml"
      
      - name: Build all Maven projects
        run: |
          echo "Starting Maven build..."
          find . -name "pom.xml" -execdir mvn -B verify \;
