name: Docs CI

on:
  push:
    paths:
      - '**.md'
      - 'docs/**'
      - '.github/workflows/docs.yaml'
  pull_request:
    paths:
      - '**.md'
      - 'docs/**'
      - '.github/workflows/docs.yaml'

jobs:
  build-docs:
    name: Generate Javadoc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Generate Javadoc
        run: mvn -B javadoc:javadoc
