name: Run Scraper

on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - '**/*.java'
      - 'pom.xml'
      - '.github/workflows/scraper-run.yaml'

jobs:
  run-scraper:
    name: Build and Run Scraper
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build project
        run: mvn -B package

      - name: Run Scraper
        run: java -cp target/classes:target/dependency/* main.Scraper
