name: Scraper with Artifact Output

on:
  workflow_dispatch:

jobs:
  run-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build project
        run: mvn -B package

      - name: Run scraper and write output
        run: |
          java -cp target/classes:target/dependency/* main.Scraper > scraped_output.txt

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: scraper-output
          path: scraped_output.txt
